### ISSUE TITLE
Vagrant intermittently hangs on adding Win81 VMware Workstation VM to domain

### ISSUE THREAD

**Issue by chrisgannon6** [SEEK-Jobs/vagrant-windows-domain#9]
Vagrant intermittently hangs on the add to domain stage. This happens about 1/5 times when vagrant up'ing a Win8.1 VM with windows_domain plugin.

My environment: 
Host: Win 7
VMware Workstation 12
Vagrant 1.8.1
vagrant plugin list:
winrm (1.3.6)
winrm-fs (0.2.3)
vagrant-share (1.1.5, system)
vagrant-triggers (0.5.2)
vagrant-vmware-workstation (4.0.8)
vagrant-vsphere (1.6.0)
vagrant-windows-domain (1.1.12)

Logs below (note the waiting for cleanup before exiting is me cancelling it after about 20 mins wait):

D:\Vagrant\win81x642>vagrant up
Bringing machine 'vagrant-windows-81' up with 'vmware_workstation' provider...
==> vagrant-windows-81: Cloning VMware VM: 'win81x64'. This can take some time..
.
==> vagrant-windows-81: Verifying vmnet devices are healthy...
==> vagrant-windows-81: Preparing network adapters...
==> vagrant-windows-81: Fixed port collision for 3389 => 3389. Now on port 2200.

==> vagrant-windows-81: Starting the VMware VM...
==> vagrant-windows-81: Waiting for machine to boot. This may take a few minutes
...
    vagrant-windows-81: WinRM address: 192.168.158.161:5985
    vagrant-windows-81: WinRM username: vagrant
    vagrant-windows-81: WinRM execution_time_limit: PT2H
    vagrant-windows-81: WinRM transport: plaintext
==> vagrant-windows-81: Machine booted and ready!
==> vagrant-windows-81: Forwarding ports...
    vagrant-windows-81: -- 3389 => 2200
    vagrant-windows-81: -- 22 => 2222
    vagrant-windows-81: -- 5985 => 55985
    vagrant-windows-81: -- 5986 => 55986
==> vagrant-windows-81: Configuring network adapters within the VM...
==> vagrant-windows-81: Configuring secondary network adapters through VMware
==> vagrant-windows-81: on Windows is not yet supported. You will need to manual
ly
==> vagrant-windows-81: configure the network adapter.
==> vagrant-windows-81: Enabling and configuring shared folders...
    vagrant-windows-81: -- D:/Vagrant/win81x642: /vagrant
==> vagrant-windows-81: Running provisioner: shell...
    vagrant-windows-81: Running: DisableUac.ps1 as c:\tmp\vagrant-shell.ps1
==> vagrant-windows-81: EnableLUA    : 0
==> vagrant-windows-81: PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_
LOCAL_MACHINE\Software\
==> vagrant-windows-81:                Microsoft\Windows\CurrentVersion\policies
\system
==> vagrant-windows-81: PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_
LOCAL_MACHINE\Software\
==> vagrant-windows-81:                Microsoft\Windows\CurrentVersion\policies

==> vagrant-windows-81: PSChildName  : system
==> vagrant-windows-81: PSDrive      : HKLM
==> vagrant-windows-81: PSProvider   : Microsoft.PowerShell.Core\Registry
==> vagrant-windows-81: Running provisioner: shell...
    vagrant-windows-81: Running: inline PowerShell script
==> vagrant-windows-81: Running provisioner: windows_domain...
Connecting guest machine to domain 'eng12.ocl' with computer name 'vmcg8105'
==> vagrant-windows-81: "Running Windows Domain Provisioner"
VERBOSE: Performing the operation "Join in domain 'eng12.ocl'" on target "vagran
t-81".==> vagrant-windows-81: Waiting for cleanup before exiting...

**Comment by mefellows** [comment]
Thanks @chrisgannon6, could you please provide a Gist containing a debug log for this when it breaks again? Instructions for verbose logging can be found here: https://www.vagrantup.com/docs/other/debugging.html

**Comment by chrisgannon6** [comment]
Thanks @mefellows, appreciate the quick response! 

I've setup the verbose logging and have been repeatedly vagrant up and vagrant destroying the VM. As soon as it occurs again I'll post the gist here.

**Comment by mefellows** [comment]
No worries - thanks @chrisgannon6.

**Comment by chrisgannon6** [comment]
@mefellows - I haven't been able to reproduce this specific issue since. I have a separate more reproducible issue around failing to rename the computer due to intermittent "directory service is busy" error, but to keep things clean I'll raise that in a separate issue report when I have debug logs for it.

**Comment by mefellows** [comment]
Thanks @chrisgannon6, feel free to create that issue and happy to deal with it.

**Comment by chrisgannon6** [comment]
Thanks :) appreciate the support!
